
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author it207440
 */
public class ATMSelector extends javax.swing.JFrame {

    /**
     * Creates new form ATMSelector
     */
    public ATMSelector() {
        initComponents();
        loadMachines();
    }

    public void loadMachines() {

        ArrayList<String> machineDetails = new ArrayList<String>();
        sqlop sql = new sqlop();
        machineDetails = sql.getMachineList();

        if (machineDetails.size() != 0) {

            for (int i = 0; i < machineDetails.size(); i++) {
                String record = machineDetails.get(i);
                String[] recordArr = record.split("~");
                cmbATM.addItem(recordArr[0] + "- " + recordArr[1]);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No machine added to Load", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblATM = new javax.swing.JLabel();
        lblATM1 = new javax.swing.JLabel();
        cmbATM = new javax.swing.JComboBox<>();
        btnGet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblATM.setFont(new java.awt.Font("Century", 0, 10)); // NOI18N
        lblATM.setText("SELECT ATM ");

        lblATM1.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        lblATM1.setText("ATM SIMULATOR");

        cmbATM.setFont(new java.awt.Font("Century", 0, 11)); // NOI18N

        btnGet.setBackground(new java.awt.Color(51, 153, 255));
        btnGet.setFont(new java.awt.Font("Century", 0, 11)); // NOI18N
        btnGet.setText("GET SIMULATOR");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblATM)
                        .addGap(27, 27, 27)
                        .addComponent(cmbATM, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblATM1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnGet)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblATM1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblATM)
                    .addComponent(cmbATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGet)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        // TODO add your handling code here:
        try {
            String atm = (cmbATM.getSelectedItem()).toString();
            String selectedATM = atm.split("-")[0].trim();
            String location = atm.split("-")[1].trim();
            sqlop sql = new sqlop();
            String details = sql.getATMDetails(selectedATM);
            String div = details.split("~")[0].trim();
            int protocol = Integer.parseInt(details.split("~")[1].trim());
            Other other = new Other();

            other.setAtm(selectedATM);
            other.setLocation(location);
            other.setDiv(div);
            other.setProtocol(protocol);

            if (div.equals("ATM") && protocol == 1) {
                new ATM().setVisible(true);
//                dispose();
            }
            if (div.equals("CRM") && protocol == 1) {
                new DDCCRM().setVisible(true);
//                dispose();
            }
            if (div.equals("CRM") && protocol == 2) {
                new NDCCRM().setVisible(true);
//                dispose();
            }
            if (div.equals("CDM") && protocol == 1) {
                JOptionPane.showMessageDialog(null, "Not Developed", "Error", JOptionPane.ERROR_MESSAGE);
//                dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGet;
    private javax.swing.JComboBox<String> cmbATM;
    private javax.swing.JLabel lblATM;
    private javax.swing.JLabel lblATM1;
    // End of variables declaration//GEN-END:variables
}
